timescaledb-single:
  enabled: true
  replicaCount: 1
  backup:
    enabled: false
  persistentVolumes:
    data:
      size: 150Gi
    wal:
      size: 20Gi
  resources:
    requests:
      cpu: 100m
      memory: 2Gi
  patroni:
    bootstrap:
      dcs:
        postgresql:
          parameters:
            shared_preload_libraries: pg_stat_statements,pg_stat_monitor,pg_stat_kcache
  affinityTemplate: |
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/component
              operator: In
              values:
              - connector
          topologyKey: "kubernetes.io/hostname"

promscale:
  enabled: true
  # If you want to use a different image, you can do so here.
  image:
    repository: timescale/promscale
  #   tag: 0.14.0
    pullPolicy: IfNotPresent
  extraArgs:
    - "--metrics.high-availability=false"
  connectionSecretName: "tobs-promscale-connection"
  resources:
    requests:
      memory: 500Mi
      cpu: 30m
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/component
              operator: In
              values:
              - timescaledb
          topologyKey: "kubernetes.io/hostname"

kube-prometheus-stack:
  enabled: true
  defaultRules:
    rules:
      etcd: false
      kubeControllerManager: false
      kubeProxy: false
      kubeScheduler: false
  kubeControllerManager:
    enabled: false
  kubeProxy:
    enabled: false
  kubeScheduler:
    enabled: false
  kubeEtcd:
    enabled: false
  alertmanager:
    enabled: false
  # This prometheus is monitoring the cluster. Do not use it for load generation.
  prometheus:
    prometheusSpec:
      remoteRead: []
      remoteWrite: []
      replicas: 1
      additionalScrapeConfigsSecret:
        enabled: false
      ruleNamespaceSelector: {}
      serviceMonitorNamespaceSelector: {}
      podMonitorNamespaceSelector: {}
      probeNamespaceSelector: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                  - timescaledb
              topologyKey: "kubernetes.io/hostname"
          - weight: 50
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                  - connector
              topologyKey: "kubernetes.io/hostname"
  grafana:
    enabled: true
    env:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Editor"
    envValueFrom:
      GRAFANA_PASSWORD:
    prometheus:
      datasource:
        enabled: true
        url: "http://{{ .Release.Name }}-kube-prometheus-stack-prometheus.{{ .Release.Namespace }}.svc:9090"
    timescale:
      datasource:
        enabled: false
opentelemetry-operator:
  enabled: true
